//
// Autogenerated by Thrift Compiler (0.9.2)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;


var ttypes = require('./kraken_types');
//HELPER FUNCTIONS AND STRUCTURES

Kraken.KrakenService_ping_args = function(args) {
};
Kraken.KrakenService_ping_args.prototype = {};
Kraken.KrakenService_ping_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

Kraken.KrakenService_ping_args.prototype.write = function(output) {
  output.writeStructBegin('KrakenService_ping_args');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

Kraken.KrakenService_ping_result = function(args) {
};
Kraken.KrakenService_ping_result.prototype = {};
Kraken.KrakenService_ping_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

Kraken.KrakenService_ping_result.prototype.write = function(output) {
  output.writeStructBegin('KrakenService_ping_result');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

Kraken.KrakenService_ListArticleSources_args = function(args) {
};
Kraken.KrakenService_ListArticleSources_args.prototype = {};
Kraken.KrakenService_ListArticleSources_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

Kraken.KrakenService_ListArticleSources_args.prototype.write = function(output) {
  output.writeStructBegin('KrakenService_ListArticleSources_args');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

Kraken.KrakenService_ListArticleSources_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
  }
};
Kraken.KrakenService_ListArticleSources_result.prototype = {};
Kraken.KrakenService_ListArticleSources_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.LIST) {
        var _size38 = 0;
        var _rtmp342;
        this.success = [];
        var _etype41 = 0;
        _rtmp342 = input.readListBegin();
        _etype41 = _rtmp342.etype;
        _size38 = _rtmp342.size;
        for (var _i43 = 0; _i43 < _size38; ++_i43)
        {
          var elem44 = null;
          elem44 = new ttypes.ArticleSource();
          elem44.read(input);
          this.success.push(elem44);
        }
        input.readListEnd();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

Kraken.KrakenService_ListArticleSources_result.prototype.write = function(output) {
  output.writeStructBegin('KrakenService_ListArticleSources_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.LIST, 0);
    output.writeListBegin(Thrift.Type.STRUCT, this.success.length);
    for (var iter45 in this.success)
    {
      if (this.success.hasOwnProperty(iter45))
      {
        iter45 = this.success[iter45];
        iter45.write(output);
      }
    }
    output.writeListEnd();
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

Kraken.KrakenService_ImportDocument_args = function(args) {
  this.request = null;
  if (args) {
    if (args.request !== undefined) {
      this.request = args.request;
    }
  }
};
Kraken.KrakenService_ImportDocument_args.prototype = {};
Kraken.KrakenService_ImportDocument_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.request = new ttypes.GenericDocumentRequest();
        this.request.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

Kraken.KrakenService_ImportDocument_args.prototype.write = function(output) {
  output.writeStructBegin('KrakenService_ImportDocument_args');
  if (this.request !== null && this.request !== undefined) {
    output.writeFieldBegin('request', Thrift.Type.STRUCT, 1);
    this.request.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

Kraken.KrakenService_ImportDocument_result = function(args) {
  this.success = null;
  this.validationError = null;
  if (args instanceof ttypes.ValidationError) {
    this.validationError = args;
    return;
  }
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
    if (args.validationError !== undefined) {
      this.validationError = args.validationError;
    }
  }
};
Kraken.KrakenService_ImportDocument_result.prototype = {};
Kraken.KrakenService_ImportDocument_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new ttypes.ImportedDocument();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.validationError = new ttypes.ValidationError();
        this.validationError.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

Kraken.KrakenService_ImportDocument_result.prototype.write = function(output) {
  output.writeStructBegin('KrakenService_ImportDocument_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  if (this.validationError !== null && this.validationError !== undefined) {
    output.writeFieldBegin('validationError', Thrift.Type.STRUCT, 1);
    this.validationError.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

Kraken.KrakenService_GetArticleSource_args = function(args) {
  this.request = null;
  if (args) {
    if (args.request !== undefined) {
      this.request = args.request;
    }
  }
};
Kraken.KrakenService_GetArticleSource_args.prototype = {};
Kraken.KrakenService_GetArticleSource_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.request = new ttypes.GetArticleSourceRequest();
        this.request.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

Kraken.KrakenService_GetArticleSource_args.prototype.write = function(output) {
  output.writeStructBegin('KrakenService_GetArticleSource_args');
  if (this.request !== null && this.request !== undefined) {
    output.writeFieldBegin('request', Thrift.Type.STRUCT, 1);
    this.request.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

Kraken.KrakenService_GetArticleSource_result = function(args) {
  this.success = null;
  this.validationError = null;
  if (args instanceof ttypes.ValidationError) {
    this.validationError = args;
    return;
  }
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
    if (args.validationError !== undefined) {
      this.validationError = args.validationError;
    }
  }
};
Kraken.KrakenService_GetArticleSource_result.prototype = {};
Kraken.KrakenService_GetArticleSource_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new ttypes.ArticleSource();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.validationError = new ttypes.ValidationError();
        this.validationError.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

Kraken.KrakenService_GetArticleSource_result.prototype.write = function(output) {
  output.writeStructBegin('KrakenService_GetArticleSource_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  if (this.validationError !== null && this.validationError !== undefined) {
    output.writeFieldBegin('validationError', Thrift.Type.STRUCT, 1);
    this.validationError.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

Kraken.KrakenService_ListArchiveDailyIndices_args = function(args) {
  this.request = null;
  if (args) {
    if (args.request !== undefined) {
      this.request = args.request;
    } else {
      throw new Thrift.TProtocolException(Thrift.TProtocolExceptionType.UNKNOWN, 'Required field request is unset!');
    }
  }
};
Kraken.KrakenService_ListArchiveDailyIndices_args.prototype = {};
Kraken.KrakenService_ListArchiveDailyIndices_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.request = new ttypes.ListArchiveDailyIndicesRequest();
        this.request.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

Kraken.KrakenService_ListArchiveDailyIndices_args.prototype.write = function(output) {
  output.writeStructBegin('KrakenService_ListArchiveDailyIndices_args');
  if (this.request !== null && this.request !== undefined) {
    output.writeFieldBegin('request', Thrift.Type.STRUCT, 1);
    this.request.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

Kraken.KrakenService_ListArchiveDailyIndices_result = function(args) {
  this.success = null;
  this.validationError = null;
  if (args instanceof ttypes.ValidationError) {
    this.validationError = args;
    return;
  }
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
    if (args.validationError !== undefined) {
      this.validationError = args.validationError;
    }
  }
};
Kraken.KrakenService_ListArchiveDailyIndices_result.prototype = {};
Kraken.KrakenService_ListArchiveDailyIndices_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.LIST) {
        var _size46 = 0;
        var _rtmp350;
        this.success = [];
        var _etype49 = 0;
        _rtmp350 = input.readListBegin();
        _etype49 = _rtmp350.etype;
        _size46 = _rtmp350.size;
        for (var _i51 = 0; _i51 < _size46; ++_i51)
        {
          var elem52 = null;
          elem52 = new ttypes.ArchiveDailyIndex();
          elem52.read(input);
          this.success.push(elem52);
        }
        input.readListEnd();
      } else {
        input.skip(ftype);
      }
      break;
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.validationError = new ttypes.ValidationError();
        this.validationError.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

Kraken.KrakenService_ListArchiveDailyIndices_result.prototype.write = function(output) {
  output.writeStructBegin('KrakenService_ListArchiveDailyIndices_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.LIST, 0);
    output.writeListBegin(Thrift.Type.STRUCT, this.success.length);
    for (var iter53 in this.success)
    {
      if (this.success.hasOwnProperty(iter53))
      {
        iter53 = this.success[iter53];
        iter53.write(output);
      }
    }
    output.writeListEnd();
    output.writeFieldEnd();
  }
  if (this.validationError !== null && this.validationError !== undefined) {
    output.writeFieldBegin('validationError', Thrift.Type.STRUCT, 1);
    this.validationError.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

Kraken.KrakenService_GetArchiveDailyIndex_args = function(args) {
  this.request = null;
  if (args) {
    if (args.request !== undefined) {
      this.request = args.request;
    } else {
      throw new Thrift.TProtocolException(Thrift.TProtocolExceptionType.UNKNOWN, 'Required field request is unset!');
    }
  }
};
Kraken.KrakenService_GetArchiveDailyIndex_args.prototype = {};
Kraken.KrakenService_GetArchiveDailyIndex_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.request = new ttypes.GenericDocumentRequest();
        this.request.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

Kraken.KrakenService_GetArchiveDailyIndex_args.prototype.write = function(output) {
  output.writeStructBegin('KrakenService_GetArchiveDailyIndex_args');
  if (this.request !== null && this.request !== undefined) {
    output.writeFieldBegin('request', Thrift.Type.STRUCT, 1);
    this.request.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

Kraken.KrakenService_GetArchiveDailyIndex_result = function(args) {
  this.success = null;
  this.validationError = null;
  this.documentExpiredError = null;
  if (args instanceof ttypes.ValidationError) {
    this.validationError = args;
    return;
  }
  if (args instanceof ttypes.DocumentExpiredError) {
    this.documentExpiredError = args;
    return;
  }
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
    if (args.validationError !== undefined) {
      this.validationError = args.validationError;
    }
    if (args.documentExpiredError !== undefined) {
      this.documentExpiredError = args.documentExpiredError;
    }
  }
};
Kraken.KrakenService_GetArchiveDailyIndex_result.prototype = {};
Kraken.KrakenService_GetArchiveDailyIndex_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new ttypes.ArchiveDailyIndex();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.validationError = new ttypes.ValidationError();
        this.validationError.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRUCT) {
        this.documentExpiredError = new ttypes.DocumentExpiredError();
        this.documentExpiredError.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

Kraken.KrakenService_GetArchiveDailyIndex_result.prototype.write = function(output) {
  output.writeStructBegin('KrakenService_GetArchiveDailyIndex_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  if (this.validationError !== null && this.validationError !== undefined) {
    output.writeFieldBegin('validationError', Thrift.Type.STRUCT, 1);
    this.validationError.write(output);
    output.writeFieldEnd();
  }
  if (this.documentExpiredError !== null && this.documentExpiredError !== undefined) {
    output.writeFieldBegin('documentExpiredError', Thrift.Type.STRUCT, 2);
    this.documentExpiredError.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

Kraken.KrakenService_GetImportedDocument_args = function(args) {
  this.request = null;
  if (args) {
    if (args.request !== undefined) {
      this.request = args.request;
    } else {
      throw new Thrift.TProtocolException(Thrift.TProtocolExceptionType.UNKNOWN, 'Required field request is unset!');
    }
  }
};
Kraken.KrakenService_GetImportedDocument_args.prototype = {};
Kraken.KrakenService_GetImportedDocument_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.request = new ttypes.GenericDocumentRequest();
        this.request.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

Kraken.KrakenService_GetImportedDocument_args.prototype.write = function(output) {
  output.writeStructBegin('KrakenService_GetImportedDocument_args');
  if (this.request !== null && this.request !== undefined) {
    output.writeFieldBegin('request', Thrift.Type.STRUCT, 1);
    this.request.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

Kraken.KrakenService_GetImportedDocument_result = function(args) {
  this.success = null;
  this.validationError = null;
  if (args instanceof ttypes.ValidationError) {
    this.validationError = args;
    return;
  }
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
    if (args.validationError !== undefined) {
      this.validationError = args.validationError;
    }
  }
};
Kraken.KrakenService_GetImportedDocument_result.prototype = {};
Kraken.KrakenService_GetImportedDocument_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new ttypes.ImportedDocument();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.validationError = new ttypes.ValidationError();
        this.validationError.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

Kraken.KrakenService_GetImportedDocument_result.prototype.write = function(output) {
  output.writeStructBegin('KrakenService_GetImportedDocument_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  if (this.validationError !== null && this.validationError !== undefined) {
    output.writeFieldBegin('validationError', Thrift.Type.STRUCT, 1);
    this.validationError.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

Kraken.KrakenService_ParseArchiveDailyIndex_args = function(args) {
  this.request = null;
  if (args) {
    if (args.request !== undefined) {
      this.request = args.request;
    } else {
      throw new Thrift.TProtocolException(Thrift.TProtocolExceptionType.UNKNOWN, 'Required field request is unset!');
    }
  }
};
Kraken.KrakenService_ParseArchiveDailyIndex_args.prototype = {};
Kraken.KrakenService_ParseArchiveDailyIndex_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.request = new ttypes.GenericDocumentRequest();
        this.request.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

Kraken.KrakenService_ParseArchiveDailyIndex_args.prototype.write = function(output) {
  output.writeStructBegin('KrakenService_ParseArchiveDailyIndex_args');
  if (this.request !== null && this.request !== undefined) {
    output.writeFieldBegin('request', Thrift.Type.STRUCT, 1);
    this.request.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

Kraken.KrakenService_ParseArchiveDailyIndex_result = function(args) {
  this.success = null;
  this.validationError = null;
  if (args instanceof ttypes.ValidationError) {
    this.validationError = args;
    return;
  }
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
    if (args.validationError !== undefined) {
      this.validationError = args.validationError;
    }
  }
};
Kraken.KrakenService_ParseArchiveDailyIndex_result.prototype = {};
Kraken.KrakenService_ParseArchiveDailyIndex_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new ttypes.ArchiveDailyIndex();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.validationError = new ttypes.ValidationError();
        this.validationError.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

Kraken.KrakenService_ParseArchiveDailyIndex_result.prototype.write = function(output) {
  output.writeStructBegin('KrakenService_ParseArchiveDailyIndex_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  if (this.validationError !== null && this.validationError !== undefined) {
    output.writeFieldBegin('validationError', Thrift.Type.STRUCT, 1);
    this.validationError.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

Kraken.KrakenService_GetArticle_args = function(args) {
  this.request = null;
  if (args) {
    if (args.request !== undefined) {
      this.request = args.request;
    } else {
      throw new Thrift.TProtocolException(Thrift.TProtocolExceptionType.UNKNOWN, 'Required field request is unset!');
    }
  }
};
Kraken.KrakenService_GetArticle_args.prototype = {};
Kraken.KrakenService_GetArticle_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.request = new ttypes.GenericDocumentRequest();
        this.request.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

Kraken.KrakenService_GetArticle_args.prototype.write = function(output) {
  output.writeStructBegin('KrakenService_GetArticle_args');
  if (this.request !== null && this.request !== undefined) {
    output.writeFieldBegin('request', Thrift.Type.STRUCT, 1);
    this.request.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

Kraken.KrakenService_GetArticle_result = function(args) {
  this.success = null;
  this.validationError = null;
  if (args instanceof ttypes.ValidationError) {
    this.validationError = args;
    return;
  }
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
    if (args.validationError !== undefined) {
      this.validationError = args.validationError;
    }
  }
};
Kraken.KrakenService_GetArticle_result.prototype = {};
Kraken.KrakenService_GetArticle_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new ttypes.Article();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.validationError = new ttypes.ValidationError();
        this.validationError.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

Kraken.KrakenService_GetArticle_result.prototype.write = function(output) {
  output.writeStructBegin('KrakenService_GetArticle_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  if (this.validationError !== null && this.validationError !== undefined) {
    output.writeFieldBegin('validationError', Thrift.Type.STRUCT, 1);
    this.validationError.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

Kraken.KrakenService_ParseArticle_args = function(args) {
  this.request = null;
  if (args) {
    if (args.request !== undefined) {
      this.request = args.request;
    } else {
      throw new Thrift.TProtocolException(Thrift.TProtocolExceptionType.UNKNOWN, 'Required field request is unset!');
    }
  }
};
Kraken.KrakenService_ParseArticle_args.prototype = {};
Kraken.KrakenService_ParseArticle_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.request = new ttypes.GenericDocumentRequest();
        this.request.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

Kraken.KrakenService_ParseArticle_args.prototype.write = function(output) {
  output.writeStructBegin('KrakenService_ParseArticle_args');
  if (this.request !== null && this.request !== undefined) {
    output.writeFieldBegin('request', Thrift.Type.STRUCT, 1);
    this.request.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

Kraken.KrakenService_ParseArticle_result = function(args) {
  this.success = null;
  this.validationError = null;
  this.parseError = null;
  if (args instanceof ttypes.ValidationError) {
    this.validationError = args;
    return;
  }
  if (args instanceof ttypes.ParseError) {
    this.parseError = args;
    return;
  }
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
    if (args.validationError !== undefined) {
      this.validationError = args.validationError;
    }
    if (args.parseError !== undefined) {
      this.parseError = args.parseError;
    }
  }
};
Kraken.KrakenService_ParseArticle_result.prototype = {};
Kraken.KrakenService_ParseArticle_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new ttypes.Article();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.validationError = new ttypes.ValidationError();
        this.validationError.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRUCT) {
        this.parseError = new ttypes.ParseError();
        this.parseError.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

Kraken.KrakenService_ParseArticle_result.prototype.write = function(output) {
  output.writeStructBegin('KrakenService_ParseArticle_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  if (this.validationError !== null && this.validationError !== undefined) {
    output.writeFieldBegin('validationError', Thrift.Type.STRUCT, 1);
    this.validationError.write(output);
    output.writeFieldEnd();
  }
  if (this.parseError !== null && this.parseError !== undefined) {
    output.writeFieldBegin('parseError', Thrift.Type.STRUCT, 2);
    this.parseError.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

Kraken.KrakenServiceClient = exports.Client = function(output, pClass) {
    this.output = output;
    this.pClass = pClass;
    this._seqid = 0;
    this._reqs = {};
};
Kraken.KrakenServiceClient.prototype = {};
Kraken.KrakenServiceClient.prototype.seqid = function() { return this._seqid; }
Kraken.KrakenServiceClient.prototype.new_seqid = function() { return this._seqid += 1; }
Kraken.KrakenServiceClient.prototype.ping = function(callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_ping();
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_ping();
  }
};

Kraken.KrakenServiceClient.prototype.send_ping = function() {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('ping', Thrift.MessageType.CALL, this.seqid());
  var args = new Kraken.KrakenService_ping_args();
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

Kraken.KrakenServiceClient.prototype.recv_ping = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new Kraken.KrakenService_ping_result();
  result.read(input);
  input.readMessageEnd();

  callback(null)
};
Kraken.KrakenServiceClient.prototype.ListArticleSources = function(callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_ListArticleSources();
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_ListArticleSources();
  }
};

Kraken.KrakenServiceClient.prototype.send_ListArticleSources = function() {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('ListArticleSources', Thrift.MessageType.CALL, this.seqid());
  var args = new Kraken.KrakenService_ListArticleSources_args();
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

Kraken.KrakenServiceClient.prototype.recv_ListArticleSources = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new Kraken.KrakenService_ListArticleSources_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('ListArticleSources failed: unknown result');
};
Kraken.KrakenServiceClient.prototype.ImportDocument = function(request, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_ImportDocument(request);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_ImportDocument(request);
  }
};

Kraken.KrakenServiceClient.prototype.send_ImportDocument = function(request) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('ImportDocument', Thrift.MessageType.CALL, this.seqid());
  var args = new Kraken.KrakenService_ImportDocument_args();
  args.request = request;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

Kraken.KrakenServiceClient.prototype.recv_ImportDocument = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new Kraken.KrakenService_ImportDocument_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.validationError) {
    return callback(result.validationError);
  }
  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('ImportDocument failed: unknown result');
};
Kraken.KrakenServiceClient.prototype.GetArticleSource = function(request, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_GetArticleSource(request);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_GetArticleSource(request);
  }
};

Kraken.KrakenServiceClient.prototype.send_GetArticleSource = function(request) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('GetArticleSource', Thrift.MessageType.CALL, this.seqid());
  var args = new Kraken.KrakenService_GetArticleSource_args();
  args.request = request;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

Kraken.KrakenServiceClient.prototype.recv_GetArticleSource = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new Kraken.KrakenService_GetArticleSource_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.validationError) {
    return callback(result.validationError);
  }
  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('GetArticleSource failed: unknown result');
};
Kraken.KrakenServiceClient.prototype.ListArchiveDailyIndices = function(request, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_ListArchiveDailyIndices(request);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_ListArchiveDailyIndices(request);
  }
};

Kraken.KrakenServiceClient.prototype.send_ListArchiveDailyIndices = function(request) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('ListArchiveDailyIndices', Thrift.MessageType.CALL, this.seqid());
  var args = new Kraken.KrakenService_ListArchiveDailyIndices_args();
  args.request = request;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

Kraken.KrakenServiceClient.prototype.recv_ListArchiveDailyIndices = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new Kraken.KrakenService_ListArchiveDailyIndices_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.validationError) {
    return callback(result.validationError);
  }
  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('ListArchiveDailyIndices failed: unknown result');
};
Kraken.KrakenServiceClient.prototype.GetArchiveDailyIndex = function(request, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_GetArchiveDailyIndex(request);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_GetArchiveDailyIndex(request);
  }
};

Kraken.KrakenServiceClient.prototype.send_GetArchiveDailyIndex = function(request) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('GetArchiveDailyIndex', Thrift.MessageType.CALL, this.seqid());
  var args = new Kraken.KrakenService_GetArchiveDailyIndex_args();
  args.request = request;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

Kraken.KrakenServiceClient.prototype.recv_GetArchiveDailyIndex = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new Kraken.KrakenService_GetArchiveDailyIndex_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.validationError) {
    return callback(result.validationError);
  }
  if (null !== result.documentExpiredError) {
    return callback(result.documentExpiredError);
  }
  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('GetArchiveDailyIndex failed: unknown result');
};
Kraken.KrakenServiceClient.prototype.GetImportedDocument = function(request, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_GetImportedDocument(request);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_GetImportedDocument(request);
  }
};

Kraken.KrakenServiceClient.prototype.send_GetImportedDocument = function(request) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('GetImportedDocument', Thrift.MessageType.CALL, this.seqid());
  var args = new Kraken.KrakenService_GetImportedDocument_args();
  args.request = request;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

Kraken.KrakenServiceClient.prototype.recv_GetImportedDocument = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new Kraken.KrakenService_GetImportedDocument_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.validationError) {
    return callback(result.validationError);
  }
  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('GetImportedDocument failed: unknown result');
};
Kraken.KrakenServiceClient.prototype.ParseArchiveDailyIndex = function(request, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_ParseArchiveDailyIndex(request);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_ParseArchiveDailyIndex(request);
  }
};

Kraken.KrakenServiceClient.prototype.send_ParseArchiveDailyIndex = function(request) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('ParseArchiveDailyIndex', Thrift.MessageType.CALL, this.seqid());
  var args = new Kraken.KrakenService_ParseArchiveDailyIndex_args();
  args.request = request;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

Kraken.KrakenServiceClient.prototype.recv_ParseArchiveDailyIndex = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new Kraken.KrakenService_ParseArchiveDailyIndex_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.validationError) {
    return callback(result.validationError);
  }
  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('ParseArchiveDailyIndex failed: unknown result');
};
Kraken.KrakenServiceClient.prototype.GetArticle = function(request, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_GetArticle(request);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_GetArticle(request);
  }
};

Kraken.KrakenServiceClient.prototype.send_GetArticle = function(request) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('GetArticle', Thrift.MessageType.CALL, this.seqid());
  var args = new Kraken.KrakenService_GetArticle_args();
  args.request = request;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

Kraken.KrakenServiceClient.prototype.recv_GetArticle = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new Kraken.KrakenService_GetArticle_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.validationError) {
    return callback(result.validationError);
  }
  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('GetArticle failed: unknown result');
};
Kraken.KrakenServiceClient.prototype.ParseArticle = function(request, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_ParseArticle(request);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_ParseArticle(request);
  }
};

Kraken.KrakenServiceClient.prototype.send_ParseArticle = function(request) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('ParseArticle', Thrift.MessageType.CALL, this.seqid());
  var args = new Kraken.KrakenService_ParseArticle_args();
  args.request = request;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

Kraken.KrakenServiceClient.prototype.recv_ParseArticle = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new Kraken.KrakenService_ParseArticle_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.validationError) {
    return callback(result.validationError);
  }
  if (null !== result.parseError) {
    return callback(result.parseError);
  }
  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('ParseArticle failed: unknown result');
};
Kraken.KrakenServiceProcessor = exports.Processor = function(handler) {
  this._handler = handler
}
Kraken.KrakenServiceProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.EXCEPTION, r.rseqid);
    x.write(output);
    output.writeMessageEnd();
    output.flush();
  }
}

Kraken.KrakenServiceProcessor.prototype.process_ping = function(seqid, input, output) {
  var args = new Kraken.KrakenService_ping_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.ping.length === 0) {
    Q.fcall(this._handler.ping)
      .then(function(result) {
        var result = new Kraken.KrakenService_ping_result({success: result});
        output.writeMessageBegin("ping", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new Kraken.KrakenService_ping_result(err);
        output.writeMessageBegin("ping", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.ping( function (err, result) {
      var result = new Kraken.KrakenService_ping_result((err != null ? err : {success: result}));
      output.writeMessageBegin("ping", Thrift.MessageType.REPLY, seqid);
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

Kraken.KrakenServiceProcessor.prototype.process_ListArticleSources = function(seqid, input, output) {
  var args = new Kraken.KrakenService_ListArticleSources_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.ListArticleSources.length === 0) {
    Q.fcall(this._handler.ListArticleSources)
      .then(function(result) {
        var result = new Kraken.KrakenService_ListArticleSources_result({success: result});
        output.writeMessageBegin("ListArticleSources", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new Kraken.KrakenService_ListArticleSources_result(err);
        output.writeMessageBegin("ListArticleSources", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.ListArticleSources( function (err, result) {
      var result = new Kraken.KrakenService_ListArticleSources_result((err != null ? err : {success: result}));
      output.writeMessageBegin("ListArticleSources", Thrift.MessageType.REPLY, seqid);
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

Kraken.KrakenServiceProcessor.prototype.process_ImportDocument = function(seqid, input, output) {
  var args = new Kraken.KrakenService_ImportDocument_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.ImportDocument.length === 1) {
    Q.fcall(this._handler.ImportDocument, args.request)
      .then(function(result) {
        var result = new Kraken.KrakenService_ImportDocument_result({success: result});
        output.writeMessageBegin("ImportDocument", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new Kraken.KrakenService_ImportDocument_result(err);
        output.writeMessageBegin("ImportDocument", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.ImportDocument(args.request,  function (err, result) {
      var result = new Kraken.KrakenService_ImportDocument_result((err != null ? err : {success: result}));
      output.writeMessageBegin("ImportDocument", Thrift.MessageType.REPLY, seqid);
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

Kraken.KrakenServiceProcessor.prototype.process_GetArticleSource = function(seqid, input, output) {
  var args = new Kraken.KrakenService_GetArticleSource_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.GetArticleSource.length === 1) {
    Q.fcall(this._handler.GetArticleSource, args.request)
      .then(function(result) {
        var result = new Kraken.KrakenService_GetArticleSource_result({success: result});
        output.writeMessageBegin("GetArticleSource", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new Kraken.KrakenService_GetArticleSource_result(err);
        output.writeMessageBegin("GetArticleSource", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.GetArticleSource(args.request,  function (err, result) {
      var result = new Kraken.KrakenService_GetArticleSource_result((err != null ? err : {success: result}));
      output.writeMessageBegin("GetArticleSource", Thrift.MessageType.REPLY, seqid);
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

Kraken.KrakenServiceProcessor.prototype.process_ListArchiveDailyIndices = function(seqid, input, output) {
  var args = new Kraken.KrakenService_ListArchiveDailyIndices_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.ListArchiveDailyIndices.length === 1) {
    Q.fcall(this._handler.ListArchiveDailyIndices, args.request)
      .then(function(result) {
        var result = new Kraken.KrakenService_ListArchiveDailyIndices_result({success: result});
        output.writeMessageBegin("ListArchiveDailyIndices", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new Kraken.KrakenService_ListArchiveDailyIndices_result(err);
        output.writeMessageBegin("ListArchiveDailyIndices", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.ListArchiveDailyIndices(args.request,  function (err, result) {
      var result = new Kraken.KrakenService_ListArchiveDailyIndices_result((err != null ? err : {success: result}));
      output.writeMessageBegin("ListArchiveDailyIndices", Thrift.MessageType.REPLY, seqid);
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

Kraken.KrakenServiceProcessor.prototype.process_GetArchiveDailyIndex = function(seqid, input, output) {
  var args = new Kraken.KrakenService_GetArchiveDailyIndex_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.GetArchiveDailyIndex.length === 1) {
    Q.fcall(this._handler.GetArchiveDailyIndex, args.request)
      .then(function(result) {
        var result = new Kraken.KrakenService_GetArchiveDailyIndex_result({success: result});
        output.writeMessageBegin("GetArchiveDailyIndex", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new Kraken.KrakenService_GetArchiveDailyIndex_result(err);
        output.writeMessageBegin("GetArchiveDailyIndex", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.GetArchiveDailyIndex(args.request,  function (err, result) {
      var result = new Kraken.KrakenService_GetArchiveDailyIndex_result((err != null ? err : {success: result}));
      output.writeMessageBegin("GetArchiveDailyIndex", Thrift.MessageType.REPLY, seqid);
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

Kraken.KrakenServiceProcessor.prototype.process_GetImportedDocument = function(seqid, input, output) {
  var args = new Kraken.KrakenService_GetImportedDocument_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.GetImportedDocument.length === 1) {
    Q.fcall(this._handler.GetImportedDocument, args.request)
      .then(function(result) {
        var result = new Kraken.KrakenService_GetImportedDocument_result({success: result});
        output.writeMessageBegin("GetImportedDocument", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new Kraken.KrakenService_GetImportedDocument_result(err);
        output.writeMessageBegin("GetImportedDocument", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.GetImportedDocument(args.request,  function (err, result) {
      var result = new Kraken.KrakenService_GetImportedDocument_result((err != null ? err : {success: result}));
      output.writeMessageBegin("GetImportedDocument", Thrift.MessageType.REPLY, seqid);
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

Kraken.KrakenServiceProcessor.prototype.process_ParseArchiveDailyIndex = function(seqid, input, output) {
  var args = new Kraken.KrakenService_ParseArchiveDailyIndex_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.ParseArchiveDailyIndex.length === 1) {
    Q.fcall(this._handler.ParseArchiveDailyIndex, args.request)
      .then(function(result) {
        var result = new Kraken.KrakenService_ParseArchiveDailyIndex_result({success: result});
        output.writeMessageBegin("ParseArchiveDailyIndex", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new Kraken.KrakenService_ParseArchiveDailyIndex_result(err);
        output.writeMessageBegin("ParseArchiveDailyIndex", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.ParseArchiveDailyIndex(args.request,  function (err, result) {
      var result = new Kraken.KrakenService_ParseArchiveDailyIndex_result((err != null ? err : {success: result}));
      output.writeMessageBegin("ParseArchiveDailyIndex", Thrift.MessageType.REPLY, seqid);
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

Kraken.KrakenServiceProcessor.prototype.process_GetArticle = function(seqid, input, output) {
  var args = new Kraken.KrakenService_GetArticle_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.GetArticle.length === 1) {
    Q.fcall(this._handler.GetArticle, args.request)
      .then(function(result) {
        var result = new Kraken.KrakenService_GetArticle_result({success: result});
        output.writeMessageBegin("GetArticle", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new Kraken.KrakenService_GetArticle_result(err);
        output.writeMessageBegin("GetArticle", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.GetArticle(args.request,  function (err, result) {
      var result = new Kraken.KrakenService_GetArticle_result((err != null ? err : {success: result}));
      output.writeMessageBegin("GetArticle", Thrift.MessageType.REPLY, seqid);
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

Kraken.KrakenServiceProcessor.prototype.process_ParseArticle = function(seqid, input, output) {
  var args = new Kraken.KrakenService_ParseArticle_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.ParseArticle.length === 1) {
    Q.fcall(this._handler.ParseArticle, args.request)
      .then(function(result) {
        var result = new Kraken.KrakenService_ParseArticle_result({success: result});
        output.writeMessageBegin("ParseArticle", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new Kraken.KrakenService_ParseArticle_result(err);
        output.writeMessageBegin("ParseArticle", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.ParseArticle(args.request,  function (err, result) {
      var result = new Kraken.KrakenService_ParseArticle_result((err != null ? err : {success: result}));
      output.writeMessageBegin("ParseArticle", Thrift.MessageType.REPLY, seqid);
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

